# docker-compose.yml
name: aditya-okke-helpdesk
services:
  mongodb:
    image: mongo:7
    container_name: helpdesk_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      # Uncomment the following lines if you want to set up authentication for MongoDB
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: helpdesk
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: >
        echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}) }"
        | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30

  redis:
    image: redis:7-alpine
    container_name: helpdesk_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass redispassword
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: