# docker-compose.yml
name: aditya-okke-helpdesk
services:
  mongodb:
    image: mongo:7
    container_name: helpdesk_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: helpdesk
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: helpdesk_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass redispassword
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data: